Starting test 1
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 1 exceeded maximum allowed time of 30
Finished test 1
Test 1:		FAILED
Starting test 2
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 2 exceeded maximum allowed time of 30
Finished test 2
Test 2:		FAILED
Starting test 3
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 3 exceeded maximum allowed time of 30
Finished test 3
Test 3:		FAILED
Starting test 4
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 4 exceeded maximum allowed time of 30
Finished test 4
Test 4:		FAILED
Starting test 5
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 5 exceeded maximum allowed time of 30
Finished test 5
Test 5:		FAILED
Starting test 6
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 6 exceeded maximum allowed time of 30
Finished test 6
Test 6:		FAILED
Starting test 7
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 7 exceeded maximum allowed time of 30
Finished test 7
Test 7:		FAILED
Starting test 8
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 8 exceeded maximum allowed time of 30
Finished test 8
Test 8:		FAILED
Starting test 9
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 9 exceeded maximum allowed time of 60
Finished test 9
Test 9:		FAILED
Starting test 10
Traceback (most recent call last):
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 74, in <module>
    main()
  File "D:\ACS-CTI\anul3\sem2\asc\teme\tema1\1-marketplace\skel\test.py", line 60, in main
    producer.start()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 920, in start
    raise RuntimeError("thread.__init__() not called")
RuntimeError: thread.__init__() not called
TIMEOUT. Test 10 exceeded maximum allowed time of 60
Finished test 10
Test 10:		FAILED

Run pylint

************* Module consumer
tema\consumer.py:17:4: W0231: __init__ method from base class 'Thread' is not called (super-init-not-called)
tema\consumer.py:34:8: W0107: Unnecessary pass statement (unnecessary-pass)
************* Module marketplace
tema\marketplace.py:22:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:28:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:42:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:50:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:64:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:76:8: W0107: Unnecessary pass statement (unnecessary-pass)
tema\marketplace.py:85:8: W0107: Unnecessary pass statement (unnecessary-pass)
************* Module producer
tema\producer.py:17:4: W0231: __init__ method from base class 'Thread' is not called (super-init-not-called)
tema\producer.py:34:8: W0107: Unnecessary pass statement (unnecessary-pass)

-----------------------------------
Your code has been rated at 6.94/10

